# Generated by Django 2.2.28 on 2023-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.BigIntegerField()),
                ('wallet_name', models.CharField(blank=True, max_length=256, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=256, null=True)),
                ('chain_support', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
